name       : haskell-either
version    : '5'
release    : 3
source     :
    - http://hackage.haskell.org/package/either-5/either-5.tar.gz : 75cee27641a34f80e6c71f82469a76c7f51d23a522e792e2733269ebf7cbf420
license    : BSD-3-Clause
component  : programing.haskell
summary    : An either monad transformer
description: |
    An either monad transformer
builddeps  :
    - haskell-cabal-install
    - haskell-free
    - haskell-mmorph
    - haskell-monad-control
    - haskell-monadrandom
    - haskell-semigroupoids
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
