name       : haskell-either
version    : 5.0.1.1
release    : 4
source     :
    - https://hackage.haskell.org/package/either-5.0.1.1/either-5.0.1.1.tar.gz : 0243d51d6a02ecb541e4854a588a9b6219a4690ebcbdb79387dd14ad519cdf27
license    : BSD-3-Clause
component  : programing.haskell
summary    : An either monad transformer
description: |
    An either monad transformer
builddeps  :
    - haskell-cabal-install
    - haskell-profunctors-devel
    - haskell-semigroupoids-devel
rundeps    :
    - devel:
        - haskell-profunctors-devel
        - haskell-semigroupoids-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
