name       : haskell-either
version    : 4.4.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/either-4.4.1.1/either-4.4.1.1.tar.gz : b087cb0fb63fec2fbdcac05fef0d03751daef5deb86cda3c732b9a6a31e634d3
license    : BSD-3-Clause
component  : programing.haskell
summary    : An either monad transformer
description: |
    An either monad transformer
builddeps  :
    - haskell-cabal-install
    - haskell-free
    - haskell-mmorph
    - haskell-monad-control
    - haskell-monadrandom
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
